### ISSUE TITLE
Not working under TWM

### ISSUE THREAD

**Issue by cuu** [AndrewCRMartin/xraise#1]
:)

**Comment by AndrewCRMartin** [comment]
Thanks... 

As in the COPYRIGHT message, most of the code came from `xdotool`: https://github.com/jordansissel/xdotool

Can you let me know `xdotool` this works correctly under TWM? If it does, I can update the borrowed bits of code. If not, please report the problem to them. It's possible that TWM is not sufficiently X compliant that it will ever work.
